---
output: html_document
editor_options: 
  chunk_output_type: console
---

SETUP
```{r}
#### Disable scientific notation in variables
options(scipen = 999)
options(warn = -1)
hg38TotalBP <- 3272116950

suppressMessages(library(GenomicRanges))
suppressMessages(library(Rsamtools))
suppressMessages(library(GenomicAlignments))
suppressMessages(library(stats4))
suppressMessages(library(BiocGenerics))
suppressMessages(library(parallel))
suppressMessages(library(genomation))
suppressMessages(library(seqLogo))
suppressMessages(library(ChIPpeakAnno))
suppressMessages(library(rlist))
suppressMessages(library(TxDb.Hsapiens.UCSC.hg38.knownGene))

generateNullFP <- function(iterations, inputSignal, analysisWidth, motifWidth){
  # This script will be used to generate indiviudal null models at predicted motif binding sites across the genome when scanning for TF footprinting from ATAC-seq data. To generate these null models, the current model will need to:
  # Consider the total signal (number of insertions) at each specific ~200 bp locus
  # Use the actul underlying reference sequence of that ~200 bp stretch from the hg38 reference genome
  # Use published or experimentally derived models of Tn5 sequence specific insertion bias
  # For each locus, build a probablistic model of insertion site distributions based on the underlying sequence and Tn5 insertion bias
  # Generate the null model graph by weighted random residstribution of the total observed signal at that site
  # Importantly, the null model must be generated separately for the plus and minus strand, it can then be combined and compared to the combined signal from the reference observed signal at that sequence
  # These null models can then be used for a site-by-site comparison of the null model against the observed data to accept or reject the null hypothesis
  # iterations = number of iterations
  # inputSignals = unique values for total signal
  # analysisWidth = total bp in region of interest (flank + background + motif)
  # motifWidth = motif width
  
  # declare vector of size n to store average motif signal values
  averages <- c()
  
  # generate the null models and calculate motif averages
  for (a in 1:iterations){
    
    # declare the null vector
    null <- c(1:(analysisWidth))
    
    # randomly distribute the total signal
    # size = the number of values to distribute
    # prob = probability of each site
    # length = length of the generated vector
    null <- c(as.vector(rmultinom(1, size=inputSignal, prob=rep(1, length(null)))))
    
    ## Calculate the mean signal in motif region
    motifStart <- ((analysisWidth - motifWidth)/2)
    motifEnd <- (motifStart + motifWidth)
    motifAvg <- (sum(null[motifStart:motifEnd])) / motifWidth
    
    ## Store the average values
    averages[a] <- motifAvg
    
  } # end for (a in 1:n)
  return(averages)
} # end generateNullFP function

analyzeFP <- function(geneName, geneSitesPath, sampleName, sampleBamPath){
  
  cat("Input variables:", "\n", geneName, "\n", geneSitesPath, "\n", sampleName, "\n", sampleBamPath, "\n")
  cat("Reading sites RDS", "\n")
  sites <- readRDS(geneSitesPath)
  inputSites <- sites[[1]][["sites"]]
  inputSites@elementType <- "GENE"
  inputSites <- keepStandardChromosomes(inputSites, pruning.mode="coarse")
  inputSites <- trim(inputSites)
  cat("Checking number of sites and motif width", "\n")
  motifWidth <- length(sites[[1]][["PWM"]][1,])
  numSites <- length(inputSites)
  cat("Extending sites", "\n")
  extSites <- promoters(inputSites, upstream = 250, downstream = (250 + motifWidth), use.names=TRUE)
  extSites <- keepStandardChromosomes(extSites, pruning.mode="coarse")
  extSites <- trim(extSites)
  cat("Loading reads from bam file", "\n")
  param <- ScanBamParam(which = extSites)
  bamIn <- readGAlignments(sampleBamPath, param = param)
  grIn <- granges(bamIn)
  grIn <- keepStandardChromosomes(grIn, pruning.mode="coarse")
  grIn <- trim(grIn)
  cat("Resizing reads and shifting +4/-5", "\n")
  grIn2 <- resize(grIn, width = 1)
  plusIdx <- which(strand(grIn2) == "+")
  minusIdx <- which(strand(grIn2) == "-")
  grPlus <- grIn2[plusIdx]
  grMinus <- grIn2[minusIdx]
  grPlusShifted <- shift(grPlus, shift=4L)
  grMinusShifted <- shift(grMinus, shift=-5L)
  grMerged <- c(grPlusShifted, grMinusShifted)
  shiftedInsertions <- grMerged
  cat("Generating insertion matrix", "\n")
  insRLE <- coverage(grMerged)
  insViews <- Views(insRLE, extSites)
  insMatrix <- as.matrix(insViews)
  cat("Calculating normalization factors", "\n")
  libSize <- length(bamIn)
  coverageSize <- sum(as.numeric(width(reduce(grIn, ignore.strand=TRUE))))
  libFactor <- libSize / coverageSize
  cat("Calculating raw sites basic footprint stats", "\n")
  rawSiteBasicStats <- matrix(data = NA, nrow = numSites, ncol = 10)
  colnames(rawSiteBasicStats) <- c("Site index", "Total signal", "Total signal per bp", "Motif signal per bp",
                                 "Flank signal per bp", "Background signal per bp", "Wide flank signal per bp",
                                 "Flank / Background", "Motif / Flank", "Motif / Wide Flank")
  for (b in 1:numSites){
    rawSiteBasicStats[b,1] <- b # Site index
    rawSiteBasicStats[b,2] <- sum(insMatrix[b,]) # Total signal
    rawSiteBasicStats[b,3] <- rawSiteBasicStats[b,2] / (500 + motifWidth) # Total signal per bp
    rawSiteBasicStats[b,4] <- sum(insMatrix[b,(250:(250 + motifWidth))] / motifWidth) # Motif signal per bp
    rawSiteBasicStats[b,5] <- (sum(insMatrix[b,200:250]) + sum(insMatrix[b,(250 + motifWidth):(300 + motifWidth)])) / 100 # Flank signal per bp
    rawSiteBasicStats[b,6] <- (sum(insMatrix[b,1:50]) + sum(insMatrix[b,(500 + motifWidth-50):(500 + motifWidth)])) / 100 # Background signal per bp
    rawSiteBasicStats[b,7] <- (sum(insMatrix[b,1:250]) + sum(insMatrix[b,(250 + motifWidth):(500 + motifWidth)])) / 500 # Wide flank signal per bp
    rawSiteBasicStats[b,8] <- rawSiteBasicStats[b,5] / rawSiteBasicStats[b,6] # Flank / background
    rawSiteBasicStats[b,9] <- rawSiteBasicStats[b,4] / rawSiteBasicStats[b,5] # Motif / flank
    rawSiteBasicStats[b,10] <- rawSiteBasicStats[b,4] / rawSiteBasicStats[b,7] # Motif / wide flank
  } # end for (b in 1:numSites)
  cat("Analyzing insertion probability", "\n")
  rawInsProb <- c()
  for (c in 1:(500 + motifWidth)){
    rawInsProb[c] <- sum(insMatrix[,c])} # end for (c in 1:(500 + motifWidth))
  cat("Finding raw total signal", "\n")
  rawTotalSignal<- sum(rawInsProb)
  rawInsProb <- rawInsProb / rawTotalSignal
  uniqueTotalSignals <- unique(rawSiteBasicStats[,2])
  siteWidth <- 500 + motifWidth
  cat("Generating null models", "\n")
  nullModels <- matrix(data = NA, ncol = 2, nrow = length(uniqueTotalSignals))
  colnames(nullModels) <- c("Input signal", "Avg motif signal in null model")
  for (c in 1:length(uniqueTotalSignals)){
    nullVec <- generateNullFP(1000, uniqueTotalSignals[c], siteWidth, motifWidth)
    nullModels[c,1] <- uniqueTotalSignals[c]
    nullModels[c,2] <- mean(nullVec)
  } # end for (c in 1:length(uniqueTotalSignals))
  cat("Performing hypothesis testing", "\n")
  ttest <- list()
  pvalue <- c()
  tvalue <- c()
  for (d in 1:numSites){
    currentSignal <- c(rawSiteBasicStats[d,2])
    currentNullModel <- nullModels[which(nullModels[,1]==currentSignal),2]
    ttest[[d]] <- t.test(insMatrix[d,250:(250+motifWidth)], mu=currentNullModel, alternative="less", conf.level = 0.95)
    pvalue[d] <- ttest[[d]][["p.value"]]
    tvalue[d] <- ttest[[d]][["statistic"]][["t"]]} # end for (d in 1:numSites)
  cat("Performing test corrections", "\n")
  idxPvaluePass <- which(pvalue < 0.05)
  pvaluePass <- pvalue[idxPvaluePass]
  ppassNumSites <- length(idxPvaluePass)
  idxBFpass <- which(pvalue < (0.05 / numSites))
  BFpvaluePass <- pvalue[idxBFpass]
  BFpassNumSites <- length(idxBFpass)
  BHpvalue <- p.adjust(pvalue, method = "BH")
  idxBHpass <- which(BHpvalue < 0.05)
  BHpvaluePass <- pvalue[idxBHpass]
  BHpassNumSites <- length(idxBHpass)
  cat("Transferring data to storage list", "\n")
  tempList <- list()
  tempList$geneName <- geneName
  tempList$geneSitesPath <- geneSitesPath
  tempList$sampleName <- sampleName
  tempList$sampleBamPath <- sampleBamPath
  tempList$numSites <- numSites
  tempList$motifWidth <- motifWidth
  tempList$PWM <- sites[[1]][["PWM"]]
  tempList$inputSites <- inputSites
  tempList$extSites <- extSites
  tempList$insMatrix <- insMatrix
  tempList$libSize <- libSize
  tempList$coverageSize <- coverageSize
  tempList$libFactor <- libFactor
  tempList$rawSiteBasicStats <- rawSiteBasicStats
  tempList$rawInsProb <- rawInsProb
  tempList$ttest <- ttest
  tempList$pvalue <- pvalue
  tempList$tvalue <- tvalue
  tempList$idxPvaluePass <- idxPvaluePass
  tempList$pvaluePass <- pvaluePass
  tempList$ppassNumSites <- ppassNumSites
  tempList$idxBFpass <- idxBFpass
  tempList$BFpvaluePass <- BFpvaluePass
  tempList$BFpassNumSites <- BFpassNumSites
  tempList$BHpvalue <- BHpvalue
  tempList$idxBHpass <- idxBHpass
  tempList$BHpvaluePass <- BHpvaluePass
  tempList$BHpassNumSites <- BHpassNumSites
  cat("Returning data", "\n")
  return(tempList)
}

importBED <- function(bedPath){
  bedin <- readBed(bedPath, track.line = FALSE, remove.unusual = FALSE, zero.based = TRUE)
  bedin <- keepStandardChromosomes(bedin, pruning.mode="coarse")
  bedin <- trim(bedin)
  return(bedin)
}


#### INPUT FILES ##################################################################################################
bam.CR01 <- "C:\\Users\\jsk33\\Desktop\\lncap\\LNCaP-CR-01-REP1.u.bam"
bai.CR01 <- "C:\\Users\\jsk33\\Desktop\\lncap\\LNCaP-CR-01-REP1.u.bai"
bam.CR02 <- "C:\\Users\\jsk33\\Desktop\\lncap\\LNCaP-CR-02-REP1.u.bam"
bai.CR02 <- "C:\\Users\\jsk33\\Desktop\\lncap\\LNCaP-CR-02-REP1.u.bai"
bam.CR04 <- "C:\\Users\\jsk33\\Desktop\\lncap\\LNCaP-CR-04-REP1.u.bam"
bai.CR04 <- "C:\\Users\\jsk33\\Desktop\\lncap\\LNCaP-CR-04-REP1.u.bai"
bam.CR05 <- "C:\\Users\\jsk33\\Desktop\\lncap\\LNCaP-CR-05-REP1.u.bam"
bai.CR05 <- "C:\\Users\\jsk33\\Desktop\\lncap\\LNCaP-CR-05-REP1.u.bai"
bam.CR07 <- "C:\\Users\\jsk33\\Desktop\\lncap\\LNCaP-CR-07-REP1.u.bam"
bai.CR07 <- "C:\\Users\\jsk33\\Desktop\\lncap\\LNCaP-CR-07-REP1.u.bai"
bam.CR08 <- "C:\\Users\\jsk33\\Desktop\\lncap\\LNCaP-CR-08-REP1.u.bam"
bai.CR08 <- "C:\\Users\\jsk33\\Desktop\\lncap\\LNCaP-CR-08-REP1.u.bai"
bam.WT01 <- "C:\\Users\\jsk33\\Desktop\\lncap\\LNCaP-WT-01-REP1.u.bam"
bai.WT01 <- "C:\\Users\\jsk33\\Desktop\\lncap\\LNCaP-WT-01-REP1.u.bai"
bam.WT02 <- "C:\\Users\\jsk33\\Desktop\\lncap\\LNCaP-WT-02-REP1.u.bam"
bai.WT02 <- "C:\\Users\\jsk33\\Desktop\\lncap\\LNCaP-WT-02-REP1.u.bai"
##
AR.sites.path <- "C:\\Users\\jsk33\\Documents\\git\\miscLabScripts\\analysisWithAlessandroLNCaP\\AR.bindingSites.RDS"
EZH2.sites.path <- "C:\\Users\\jsk33\\Documents\\git\\miscLabScripts\\analysisWithAlessandroLNCaP\\EZH2.bindingSites.RDS"
FOXM1.sites.path <- "C:\\Users\\jsk33\\Documents\\git\\miscLabScripts\\analysisWithAlessandroLNCaP\\FOXM1.bindingSites.RDS"
MYC.sites.path <- "C:\\Users\\jsk33\\Documents\\git\\miscLabScripts\\analysisWithAlessandroLNCaP\\MYC.bindingSites.RDS"
MYCN.sites.path <- "C:\\Users\\jsk33\\Documents\\git\\miscLabScripts\\analysisWithAlessandroLNCaP\\MYCN.bindingSites.RDS"
SOX2.sites.path <- "C:\\Users\\jsk33\\Documents\\git\\miscLabScripts\\analysisWithAlessandroLNCaP\\SOX2.bindingSites.RDS"
#### INPUT FILES ##################################################################################################
```

AR
```{r}

AR.FP.data.WT01 <- analyzeFP("AR", AR.sites.path, "WT01", bam.WT01)
AR.FP.data.WT02 <- analyzeFP("AR", AR.sites.path, "WT02", bam.WT02)
AR.FP.data.CR01 <- analyzeFP("AR", AR.sites.path, "CR01", bam.CR01)
AR.FP.data.CR02 <- analyzeFP("AR", AR.sites.path, "CR02", bam.CR01)
AR.FP.data.CR04 <- analyzeFP("AR", AR.sites.path, "CR04", bam.CR01)
AR.FP.data.CR05 <- analyzeFP("AR", AR.sites.path, "CR05", bam.CR01)
AR.FP.data.CR07 <- analyzeFP("AR", AR.sites.path, "CR07", bam.CR01)
AR.FP.data.CR08 <- analyzeFP("AR", AR.sites.path, "CR08", bam.CR01)

FPdata.AR <- list()
FPdata.AR$WT01 <- AR.FP.data.WT01
FPdata.AR$WT02 <- AR.FP.data.WT02
FPdata.AR$CR01 <- AR.FP.data.CR01
FPdata.AR$CR02 <- AR.FP.data.CR02
FPdata.AR$CR04 <- AR.FP.data.CR04
FPdata.AR$CR05 <- AR.FP.data.CR05
FPdata.AR$CR07 <- AR.FP.data.CR07
FPdata.AR$CR08 <- AR.FP.data.CR08

numSites <- AR.FP.data.CR01[["numSites"]]
AR.bindingMatrix <- matrix(data = 0, nrow = 8, ncol = numSites)
rownames(AR.bindingMatrix) <- c("WT01", "WT02", "CR01", "CR02", "CR04", "CR05", "CR07", "CR08")

AR.bindingMatrix[1,AR.FP.data.WT01[["idxBFpass"]]] <- 1
AR.bindingMatrix[2,AR.FP.data.WT02[["idxBFpass"]]] <- 1
AR.bindingMatrix[3,AR.FP.data.CR01[["idxBFpass"]]] <- 1
AR.bindingMatrix[4,AR.FP.data.CR02[["idxBFpass"]]] <- 1
AR.bindingMatrix[5,AR.FP.data.CR04[["idxBFpass"]]] <- 1
AR.bindingMatrix[6,AR.FP.data.CR05[["idxBFpass"]]] <- 1
AR.bindingMatrix[7,AR.FP.data.CR07[["idxBFpass"]]] <- 1
AR.bindingMatrix[8,AR.FP.data.CR08[["idxBFpass"]]] <- 1
FPdata.AR$bindingMatrix <- AR.bindingMatrix

outPath <- "C:\\Users\\jsk33\\Documents\\git\\miscLabScripts\\analysisWithAlessandroLNCaP\\FPdata.AR.RDS"
saveRDS(FPdata.AR, file = outPath)

```

SOX2
```{r}

SOX2.FP.data.WT01 <- analyzeFP("SOX2", SOX2.sites.path, "WT01", bam.WT01)
SOX2.FP.data.WT02 <- analyzeFP("SOX2", SOX2.sites.path, "WT02", bam.WT02)
SOX2.FP.data.CR01 <- analyzeFP("SOX2", SOX2.sites.path, "CR01", bam.CR01)
SOX2.FP.data.CR02 <- analyzeFP("SOX2", SOX2.sites.path, "CR02", bam.CR01)
SOX2.FP.data.CR04 <- analyzeFP("SOX2", SOX2.sites.path, "CR04", bam.CR01)
SOX2.FP.data.CR05 <- analyzeFP("SOX2", SOX2.sites.path, "CR05", bam.CR01)
SOX2.FP.data.CR07 <- analyzeFP("SOX2", SOX2.sites.path, "CR07", bam.CR01)
SOX2.FP.data.CR08 <- analyzeFP("SOX2", SOX2.sites.path, "CR08", bam.CR01)

FPdata.SOX2 <- list()
FPdata.SOX2$WT01 <- SOX2.FP.data.WT01
FPdata.SOX2$WT02 <- SOX2.FP.data.WT02
FPdata.SOX2$CR01 <- SOX2.FP.data.CR01
FPdata.SOX2$CR02 <- SOX2.FP.data.CR02
FPdata.SOX2$CR04 <- SOX2.FP.data.CR04
FPdata.SOX2$CR05 <- SOX2.FP.data.CR05
FPdata.SOX2$CR07 <- SOX2.FP.data.CR07
FPdata.SOX2$CR08 <- SOX2.FP.data.CR08

numSites <- SOX2.FP.data.CR01[["numSites"]]
SOX2.bindingMatrix <- matrix(data = 0, nrow = 8, ncol = numSites)
rownames(SOX2.bindingMatrix) <- c("WT01", "WT02", "CR01", "CR02", "CR04", "CR05", "CR07", "CR08")

SOX2.bindingMatrix[1,SOX2.FP.data.WT01[["idxBFpass"]]] <- 1
SOX2.bindingMatrix[2,SOX2.FP.data.WT02[["idxBFpass"]]] <- 1
SOX2.bindingMatrix[3,SOX2.FP.data.CR01[["idxBFpass"]]] <- 1
SOX2.bindingMatrix[4,SOX2.FP.data.CR02[["idxBFpass"]]] <- 1
SOX2.bindingMatrix[5,SOX2.FP.data.CR04[["idxBFpass"]]] <- 1
SOX2.bindingMatrix[6,SOX2.FP.data.CR05[["idxBFpass"]]] <- 1
SOX2.bindingMatrix[7,SOX2.FP.data.CR07[["idxBFpass"]]] <- 1
SOX2.bindingMatrix[8,SOX2.FP.data.CR08[["idxBFpass"]]] <- 1
FPdata.SOX2$bindingMatrix <- SOX2.bindingMatrix

outPath <- "C:\\Users\\jsk33\\Documents\\git\\miscLabScripts\\analysisWithAlessandroLNCaP\\FPdata.SOX2.RDS"
saveRDS(FPdata.SOX2, file = outPath)

```

EZH2
```{r}

EZH2.FP.data.WT01 <- analyzeFP("EZH2", EZH2.sites.path, "WT01", bam.WT01)
EZH2.FP.data.WT02 <- analyzeFP("EZH2", EZH2.sites.path, "WT02", bam.WT02)
EZH2.FP.data.CR01 <- analyzeFP("EZH2", EZH2.sites.path, "CR01", bam.CR01)
EZH2.FP.data.CR02 <- analyzeFP("EZH2", EZH2.sites.path, "CR02", bam.CR01)
EZH2.FP.data.CR04 <- analyzeFP("EZH2", EZH2.sites.path, "CR04", bam.CR01)
EZH2.FP.data.CR05 <- analyzeFP("EZH2", EZH2.sites.path, "CR05", bam.CR01)
EZH2.FP.data.CR07 <- analyzeFP("EZH2", EZH2.sites.path, "CR07", bam.CR01)
EZH2.FP.data.CR08 <- analyzeFP("EZH2", EZH2.sites.path, "CR08", bam.CR01)

FPdata.EZH2 <- list()
FPdata.EZH2$WT01 <- EZH2.FP.data.WT01
FPdata.EZH2$WT02 <- EZH2.FP.data.WT02
FPdata.EZH2$CR01 <- EZH2.FP.data.CR01
FPdata.EZH2$CR02 <- EZH2.FP.data.CR02
FPdata.EZH2$CR04 <- EZH2.FP.data.CR04
FPdata.EZH2$CR05 <- EZH2.FP.data.CR05
FPdata.EZH2$CR07 <- EZH2.FP.data.CR07
FPdata.EZH2$CR08 <- EZH2.FP.data.CR08

numSites <- EZH2.FP.data.CR01[["numSites"]]
EZH2.bindingMatrix <- matrix(data = 0, nrow = 8, ncol = numSites)
rownames(EZH2.bindingMatrix) <- c("WT01", "WT02", "CR01", "CR02", "CR04", "CR05", "CR07", "CR08")

EZH2.bindingMatrix[1,EZH2.FP.data.WT01[["idxBFpass"]]] <- 1
EZH2.bindingMatrix[2,EZH2.FP.data.WT02[["idxBFpass"]]] <- 1
EZH2.bindingMatrix[3,EZH2.FP.data.CR01[["idxBFpass"]]] <- 1
EZH2.bindingMatrix[4,EZH2.FP.data.CR02[["idxBFpass"]]] <- 1
EZH2.bindingMatrix[5,EZH2.FP.data.CR04[["idxBFpass"]]] <- 1
EZH2.bindingMatrix[6,EZH2.FP.data.CR05[["idxBFpass"]]] <- 1
EZH2.bindingMatrix[7,EZH2.FP.data.CR07[["idxBFpass"]]] <- 1
EZH2.bindingMatrix[8,EZH2.FP.data.CR08[["idxBFpass"]]] <- 1
FPdata.EZH2$bindingMatrix <- EZH2.bindingMatrix

outPath <- "C:\\Users\\jsk33\\Documents\\git\\miscLabScripts\\analysisWithAlessandroLNCaP\\FPdata.EZH2.RDS"
saveRDS(FPdata.EZH2, file = outPath)

```

MYCN
```{r}

MYCN.FP.data.WT01 <- analyzeFP("MYCN", MYCN.sites.path, "WT01", bam.WT01)
MYCN.FP.data.WT02 <- analyzeFP("MYCN", MYCN.sites.path, "WT02", bam.WT02)
MYCN.FP.data.CR01 <- analyzeFP("MYCN", MYCN.sites.path, "CR01", bam.CR01)
MYCN.FP.data.CR02 <- analyzeFP("MYCN", MYCN.sites.path, "CR02", bam.CR01)
MYCN.FP.data.CR04 <- analyzeFP("MYCN", MYCN.sites.path, "CR04", bam.CR01)
MYCN.FP.data.CR05 <- analyzeFP("MYCN", MYCN.sites.path, "CR05", bam.CR01)
MYCN.FP.data.CR07 <- analyzeFP("MYCN", MYCN.sites.path, "CR07", bam.CR01)
MYCN.FP.data.CR08 <- analyzeFP("MYCN", MYCN.sites.path, "CR08", bam.CR01)

FPdata.MYCN <- list()
FPdata.MYCN$WT01 <- MYCN.FP.data.WT01
FPdata.MYCN$WT02 <- MYCN.FP.data.WT02
FPdata.MYCN$CR01 <- MYCN.FP.data.CR01
FPdata.MYCN$CR02 <- MYCN.FP.data.CR02
FPdata.MYCN$CR04 <- MYCN.FP.data.CR04
FPdata.MYCN$CR05 <- MYCN.FP.data.CR05
FPdata.MYCN$CR07 <- MYCN.FP.data.CR07
FPdata.MYCN$CR08 <- MYCN.FP.data.CR08

numSites <- MYCN.FP.data.CR01[["numSites"]]
MYCN.bindingMatrix <- matrix(data = 0, nrow = 8, ncol = numSites)
rownames(MYCN.bindingMatrix) <- c("WT01", "WT02", "CR01", "CR02", "CR04", "CR05", "CR07", "CR08")

MYCN.bindingMatrix[1,MYCN.FP.data.WT01[["idxBFpass"]]] <- 1
MYCN.bindingMatrix[2,MYCN.FP.data.WT02[["idxBFpass"]]] <- 1
MYCN.bindingMatrix[3,MYCN.FP.data.CR01[["idxBFpass"]]] <- 1
MYCN.bindingMatrix[4,MYCN.FP.data.CR02[["idxBFpass"]]] <- 1
MYCN.bindingMatrix[5,MYCN.FP.data.CR04[["idxBFpass"]]] <- 1
MYCN.bindingMatrix[6,MYCN.FP.data.CR05[["idxBFpass"]]] <- 1
MYCN.bindingMatrix[7,MYCN.FP.data.CR07[["idxBFpass"]]] <- 1
MYCN.bindingMatrix[8,MYCN.FP.data.CR08[["idxBFpass"]]] <- 1
FPdata.MYCN$bindingMatrix <- MYCN.bindingMatrix

outPath <- "C:\\Users\\jsk33\\Documents\\git\\miscLabScripts\\analysisWithAlessandroLNCaP\\FPdata.MYCN.RDS"
saveRDS(FPdata.MYCN, file = outPath)

```

MYC
```{r}

MYC.FP.data.WT01 <- analyzeFP("MYC", MYC.sites.path, "WT01", bam.WT01)
MYC.FP.data.WT02 <- analyzeFP("MYC", MYC.sites.path, "WT02", bam.WT02)
MYC.FP.data.CR01 <- analyzeFP("MYC", MYC.sites.path, "CR01", bam.CR01)
MYC.FP.data.CR02 <- analyzeFP("MYC", MYC.sites.path, "CR02", bam.CR01)
MYC.FP.data.CR04 <- analyzeFP("MYC", MYC.sites.path, "CR04", bam.CR01)
MYC.FP.data.CR05 <- analyzeFP("MYC", MYC.sites.path, "CR05", bam.CR01)
MYC.FP.data.CR07 <- analyzeFP("MYC", MYC.sites.path, "CR07", bam.CR01)
MYC.FP.data.CR08 <- analyzeFP("MYC", MYC.sites.path, "CR08", bam.CR01)

FPdata.MYC <- list()
FPdata.MYC$WT01 <- MYC.FP.data.WT01
FPdata.MYC$WT02 <- MYC.FP.data.WT02
FPdata.MYC$CR01 <- MYC.FP.data.CR01
FPdata.MYC$CR02 <- MYC.FP.data.CR02
FPdata.MYC$CR04 <- MYC.FP.data.CR04
FPdata.MYC$CR05 <- MYC.FP.data.CR05
FPdata.MYC$CR07 <- MYC.FP.data.CR07
FPdata.MYC$CR08 <- MYC.FP.data.CR08

numSites <- MYC.FP.data.CR01[["numSites"]]
MYC.bindingMatrix <- matrix(data = 0, nrow = 8, ncol = numSites)
rownames(MYC.bindingMatrix) <- c("WT01", "WT02", "CR01", "CR02", "CR04", "CR05", "CR07", "CR08")

MYC.bindingMatrix[1,MYC.FP.data.WT01[["idxBFpass"]]] <- 1
MYC.bindingMatrix[2,MYC.FP.data.WT02[["idxBFpass"]]] <- 1
MYC.bindingMatrix[3,MYC.FP.data.CR01[["idxBFpass"]]] <- 1
MYC.bindingMatrix[4,MYC.FP.data.CR02[["idxBFpass"]]] <- 1
MYC.bindingMatrix[5,MYC.FP.data.CR04[["idxBFpass"]]] <- 1
MYC.bindingMatrix[6,MYC.FP.data.CR05[["idxBFpass"]]] <- 1
MYC.bindingMatrix[7,MYC.FP.data.CR07[["idxBFpass"]]] <- 1
MYC.bindingMatrix[8,MYC.FP.data.CR08[["idxBFpass"]]] <- 1
FPdata.MYC$bindingMatrix <- MYC.bindingMatrix

outPath <- "C:\\Users\\jsk33\\Documents\\git\\miscLabScripts\\analysisWithAlessandroLNCaP\\FPdata.MYC.RDS"
saveRDS(FPdata.MYC, file = outPath)

```

FOXM1
```{r}

FOXM1.FP.data.WT01 <- analyzeFP("FOXM1", FOXM1.sites.path, "WT01", bam.WT01)
FOXM1.FP.data.WT02 <- analyzeFP("FOXM1", FOXM1.sites.path, "WT02", bam.WT02)
FOXM1.FP.data.CR01 <- analyzeFP("FOXM1", FOXM1.sites.path, "CR01", bam.CR01)
FOXM1.FP.data.CR02 <- analyzeFP("FOXM1", FOXM1.sites.path, "CR02", bam.CR01)
FOXM1.FP.data.CR04 <- analyzeFP("FOXM1", FOXM1.sites.path, "CR04", bam.CR01)
FOXM1.FP.data.CR05 <- analyzeFP("FOXM1", FOXM1.sites.path, "CR05", bam.CR01)
FOXM1.FP.data.CR07 <- analyzeFP("FOXM1", FOXM1.sites.path, "CR07", bam.CR01)
FOXM1.FP.data.CR08 <- analyzeFP("FOXM1", FOXM1.sites.path, "CR08", bam.CR01)

FPdata.FOXM1 <- list()
FPdata.FOXM1$WT01 <- FOXM1.FP.data.WT01
FPdata.FOXM1$WT02 <- FOXM1.FP.data.WT02
FPdata.FOXM1$CR01 <- FOXM1.FP.data.CR01
FPdata.FOXM1$CR02 <- FOXM1.FP.data.CR02
FPdata.FOXM1$CR04 <- FOXM1.FP.data.CR04
FPdata.FOXM1$CR05 <- FOXM1.FP.data.CR05
FPdata.FOXM1$CR07 <- FOXM1.FP.data.CR07
FPdata.FOXM1$CR08 <- FOXM1.FP.data.CR08

numSites <- FOXM1.FP.data.CR01[["numSites"]]
FOXM1.bindingMatrix <- matrix(data = 0, nrow = 8, ncol = numSites)
rownames(FOXM1.bindingMatrix) <- c("WT01", "WT02", "CR01", "CR02", "CR04", "CR05", "CR07", "CR08")

FOXM1.bindingMatrix[1,MYC.FP.data.WT01[["idxBFpass"]]] <- 1
FOXM1.bindingMatrix[2,MYC.FP.data.WT02[["idxBFpass"]]] <- 1
FOXM1.bindingMatrix[3,MYC.FP.data.CR01[["idxBFpass"]]] <- 1
FOXM1.bindingMatrix[4,MYC.FP.data.CR02[["idxBFpass"]]] <- 1
FOXM1.bindingMatrix[5,MYC.FP.data.CR04[["idxBFpass"]]] <- 1
FOXM1.bindingMatrix[6,MYC.FP.data.CR05[["idxBFpass"]]] <- 1
FOXM1.bindingMatrix[7,MYC.FP.data.CR07[["idxBFpass"]]] <- 1
FOXM1.bindingMatrix[8,MYC.FP.data.CR08[["idxBFpass"]]] <- 1
FPdata.FOXM1$bindingMatrix <- FOXM1.bindingMatrix

outPath <- "C:\\Users\\jsk33\\Documents\\git\\miscLabScripts\\analysisWithAlessandroLNCaP\\FPdata.FOXM1.RDS"
saveRDS(FPdata.FOXM1, file = outPath)

```

Load FP data
```{r}

FPdata.AR <- readRDS("C:\\Users\\jsk33\\Documents\\git\\miscLabScripts\\analysisWithAlessandroLNCaP\\FPdata.AR.RDS")
FPdata.SOX2 <- readRDS("C:\\Users\\jsk33\\Documents\\git\\miscLabScripts\\analysisWithAlessandroLNCaP\\FPdata.SOX2.RDS")
FPdata.EZH2 <- readRDS("C:\\Users\\jsk33\\Documents\\git\\miscLabScripts\\analysisWithAlessandroLNCaP\\FPdata.EZH2.RDS")
FPdata.MYCN <- readRDS("C:\\Users\\jsk33\\Documents\\git\\miscLabScripts\\analysisWithAlessandroLNCaP\\FPdata.MYCN.RDS")
FPdata.MYC <- readRDS("C:\\Users\\jsk33\\Documents\\git\\miscLabScripts\\analysisWithAlessandroLNCaP\\FPdata.MYC.RDS")
FPdata.FOXM1 <- readRDS("C:\\Users\\jsk33\\Documents\\git\\miscLabScripts\\analysisWithAlessandroLNCaP\\FPdata.FOXM1.RDS")

```

Plots
```{r}
install.packages("pheatmap")
library(pheatmap)

library(dplyr)

AR.matrix <- FPdata.AR[["bindingMatrix"]]
x <- AR.matrix[,1:100]
pheatmap(x)

## Subset for only locations where both WT are the same
y <- as.data.frame(AR.matrix)
z <- dplyr::filter(y, WT01 == 1, WT02 == 2)

aa <- which(y[1,] == 1 & y[2,] == 1)
ab <- which(y[1,] == 0 & y[2,] == 0)
ac <- c(aa, ab)
new <- y[1:8,ac]

new2 <- new[,24728:24828]
pheatmap(new2,
         cluster_rows = FALSE,
         cluster_cols = FALSE)


EZH2.matrix <- FPdata.EZH2[["bindingMatrix"]]
x <- EZH2.matrix[,1:100]
pheatmap(x)

FOXM1.matrix <- FPdata.FOXM1[["bindingMatrix"]]
x <- FOXM1.matrix[,1:100]
pheatmap(x)

MYC.matrix <- FPdata.MYC[["bindingMatrix"]]
x <- MYC.matrix[,1:100]
pheatmap(x)

MYCN.matrix <- FPdata.MYCN[["bindingMatrix"]]
x <- MYCN.matrix[,1:100]
pheatmap(x)

SOX2.matrix <- FPdata.SOX2[["bindingMatrix"]]
x <- SOX2.matrix[,1:100]
pheatmap(x)


```

Peaks
```{r}

ctrl.wt01.treat.cr01.peaksPath <- "C:\\Users\\jsk33\\Desktop\\diffpeaks\\ctrl-wt01.treat-cr01_peaks.narrowPeak"
ctrl.wt01.treat.cr02.peaksPath <- "C:\\Users\\jsk33\\Desktop\\diffpeaks\\ctrl-wt01.treat-cr02_peaks.narrowPeak"
ctrl.wt01.treat.cr04.peaksPath <- "C:\\Users\\jsk33\\Desktop\\diffpeaks\\ctrl-wt01.treat-cr04_peaks.narrowPeak"
ctrl.wt01.treat.cr05.peaksPath <- "C:\\Users\\jsk33\\Desktop\\diffpeaks\\ctrl-wt01.treat-cr05_peaks.narrowPeak"
ctrl.wt01.treat.cr07.peaksPath <- "C:\\Users\\jsk33\\Desktop\\diffpeaks\\ctrl-wt01.treat-cr07_peaks.narrowPeak"
ctrl.wt01.treat.cr08.peaksPath <- "C:\\Users\\jsk33\\Desktop\\diffpeaks\\ctrl-wt01.treat-cr08_peaks.narrowPeak"

ctrl.wt02.treat.cr01.peaksPath <- "C:\\Users\\jsk33\\Desktop\\diffpeaks\\ctrl-wt02.treat-cr01_peaks.narrowPeak"
ctrl.wt02.treat.cr02.peaksPath <- "C:\\Users\\jsk33\\Desktop\\diffpeaks\\ctrl-wt02.treat-cr02_peaks.narrowPeak"
ctrl.wt02.treat.cr04.peaksPath <- "C:\\Users\\jsk33\\Desktop\\diffpeaks\\ctrl-wt02.treat-cr04_peaks.narrowPeak"
ctrl.wt02.treat.cr05.peaksPath <- "C:\\Users\\jsk33\\Desktop\\diffpeaks\\ctrl-wt02.treat-cr05_peaks.narrowPeak"
ctrl.wt02.treat.cr07.peaksPath <- "C:\\Users\\jsk33\\Desktop\\diffpeaks\\ctrl-wt02.treat-cr07_peaks.narrowPeak"
ctrl.wt02.treat.cr08.peaksPath <- "C:\\Users\\jsk33\\Desktop\\diffpeaks\\ctrl-wt02.treat-cr08_peaks.narrowPeak"

ctrl.wt01.treat.cr01.peaks <- readBed(ctrl.wt01.treat.cr01.peaksPath, track.line = FALSE, remove.unusual = FALSE, zero.based = TRUE)
ctrl.wt01.treat.cr01.peaks <- keepStandardChromosomes(ctrl.wt01.treat.cr01.peaks, pruning.mode="coarse")
ctrl.wt01.treat.cr01.peaks <- trim(ctrl.wt01.treat.cr01.peaks)
ctrl.wt01.treat.cr02.peaks <- readBed(ctrl.wt01.treat.cr02.peaksPath, track.line = FALSE, remove.unusual = FALSE, zero.based = TRUE)
ctrl.wt01.treat.cr02.peaks <- keepStandardChromosomes(ctrl.wt01.treat.cr02.peaks, pruning.mode="coarse")
ctrl.wt01.treat.cr02.peaks <- trim(ctrl.wt01.treat.cr02.peaks)
ctrl.wt01.treat.cr04.peaks <- readBed(ctrl.wt01.treat.cr04.peaksPath, track.line = FALSE, remove.unusual = FALSE, zero.based = TRUE)
ctrl.wt01.treat.cr04.peaks <- keepStandardChromosomes(ctrl.wt01.treat.cr04.peaks, pruning.mode="coarse")
ctrl.wt01.treat.cr04.peaks <- trim(ctrl.wt01.treat.cr04.peaks)
ctrl.wt01.treat.cr05.peaks <- readBed(ctrl.wt01.treat.cr05.peaksPath, track.line = FALSE, remove.unusual = FALSE, zero.based = TRUE)
ctrl.wt01.treat.cr05.peaks <- keepStandardChromosomes(ctrl.wt01.treat.cr05.peaks, pruning.mode="coarse")
ctrl.wt01.treat.cr05.peaks <- trim(ctrl.wt01.treat.cr05.peaks)
ctrl.wt01.treat.cr07.peaks <- readBed(ctrl.wt01.treat.cr07.peaksPath, track.line = FALSE, remove.unusual = FALSE, zero.based = TRUE)
ctrl.wt01.treat.cr07.peaks <- keepStandardChromosomes(ctrl.wt01.treat.cr07.peaks, pruning.mode="coarse")
ctrl.wt01.treat.cr07.peaks <- trim(ctrl.wt01.treat.cr07.peaks)
ctrl.wt01.treat.cr08.peaks <- readBed(ctrl.wt01.treat.cr08.peaksPath, track.line = FALSE, remove.unusual = FALSE, zero.based = TRUE)
ctrl.wt01.treat.cr08.peaks <- keepStandardChromosomes(ctrl.wt01.treat.cr08.peaks, pruning.mode="coarse")
ctrl.wt01.treat.cr08.peaks <- trim(ctrl.wt01.treat.cr08.peaks)

ctrl.wt02.treat.cr01.peaks <- readBed(ctrl.wt02.treat.cr01.peaksPath, track.line = FALSE, remove.unusual = FALSE, zero.based = TRUE)
ctrl.wt02.treat.cr01.peaks <- keepStandardChromosomes(ctrl.wt02.treat.cr01.peaks, pruning.mode="coarse")
ctrl.wt02.treat.cr01.peaks <- trim(ctrl.wt02.treat.cr01.peaks)
ctrl.wt02.treat.cr02.peaks <- readBed(ctrl.wt02.treat.cr02.peaksPath, track.line = FALSE, remove.unusual = FALSE, zero.based = TRUE)
ctrl.wt02.treat.cr02.peaks <- keepStandardChromosomes(ctrl.wt02.treat.cr02.peaks, pruning.mode="coarse")
ctrl.wt02.treat.cr02.peaks <- trim(ctrl.wt02.treat.cr02.peaks)
ctrl.wt02.treat.cr04.peaks <- readBed(ctrl.wt02.treat.cr04.peaksPath, track.line = FALSE, remove.unusual = FALSE, zero.based = TRUE)
ctrl.wt02.treat.cr04.peaks <- keepStandardChromosomes(ctrl.wt02.treat.cr04.peaks, pruning.mode="coarse")
ctrl.wt02.treat.cr04.peaks <- trim(ctrl.wt02.treat.cr04.peaks)
ctrl.wt02.treat.cr05.peaks <- readBed(ctrl.wt02.treat.cr05.peaksPath, track.line = FALSE, remove.unusual = FALSE, zero.based = TRUE)
ctrl.wt02.treat.cr05.peaks <- keepStandardChromosomes(ctrl.wt02.treat.cr05.peaks, pruning.mode="coarse")
ctrl.wt02.treat.cr05.peaks <- trim(ctrl.wt02.treat.cr05.peaks)
ctrl.wt02.treat.cr07.peaks <- readBed(ctrl.wt02.treat.cr07.peaksPath, track.line = FALSE, remove.unusual = FALSE, zero.based = TRUE)
ctrl.wt02.treat.cr07.peaks <- keepStandardChromosomes(ctrl.wt02.treat.cr07.peaks, pruning.mode="coarse")
ctrl.wt02.treat.cr07.peaks <- trim(ctrl.wt02.treat.cr07.peaks)
ctrl.wt02.treat.cr08.peaks <- readBed(ctrl.wt02.treat.cr08.peaksPath, track.line = FALSE, remove.unusual = FALSE, zero.based = TRUE)
ctrl.wt02.treat.cr08.peaks <- keepStandardChromosomes(ctrl.wt02.treat.cr08.peaks, pruning.mode="coarse")
ctrl.wt02.treat.cr08.peaks <- trim(ctrl.wt02.treat.cr08.peaks)

```



Peak overlaps
```{r}

WT01.peaksPath <- "C:\\Users\\jsk33\\Desktop\\peaks\\LNCaP-WT-01-REP1_globalnorm_peaks.narrowPeak"
WT02.peaksPath <- "C:\\Users\\jsk33\\Desktop\\peaks\\LNCaP-WT-02-REP1_globalnorm_peaks.narrowPeak"
CR01.peaksPath <- "C:\\Users\\jsk33\\Desktop\\peaks\\LNCaP-CR-01-REP1_globalnorm_peaks.narrowPeak"
CR02.peaksPath <- "C:\\Users\\jsk33\\Desktop\\peaks\\LNCaP-CR-02-REP1_globalnorm_peaks.narrowPeak"
CR04.peaksPath <- "C:\\Users\\jsk33\\Desktop\\peaks\\LNCaP-CR-04-REP1_globalnorm_peaks.narrowPeak"
CR05.peaksPath <- "C:\\Users\\jsk33\\Desktop\\peaks\\LNCaP-CR-05-REP1_globalnorm_peaks.narrowPeak"
CR07.peaksPath <- "C:\\Users\\jsk33\\Desktop\\peaks\\LNCaP-CR-07-REP1_globalnorm_peaks.narrowPeak"
CR08.peaksPath <- "C:\\Users\\jsk33\\Desktop\\peaks\\LNCaP-CR-08-REP1_globalnorm_peaks.narrowPeak"

WT01.peaks <- importBED(WT01.peaksPath)
WT02.peaks <- importBED(WT02.peaksPath)
CR01.peaks <- importBED(CR01.peaksPath)
CR02.peaks <- importBED(CR02.peaksPath)
CR04.peaks <- importBED(CR04.peaksPath)
CR05.peaks <- importBED(CR05.peaksPath)
CR07.peaks <- importBED(CR07.peaksPath)
CR08.peaks <- importBED(CR08.peaksPath)


FPdata.AR.WT01 <- FPdata.AR[["WT01"]]
FPdata.AR.WT01.inputSites <- FPdata.AR.WT01[["inputSites"]]
WT01.AR.peak.overlap.index <- findOverlaps(FPdata.AR.WT01.inputSites, WT01.peaks)
AR.WT01.idx <- unique(WT01.AR.peak.overlap.index@from)

FPdata.AR.WT02 <- FPdata.AR[["WT02"]]
FPdata.AR.WT02.inputSites <- FPdata.AR.WT02[["inputSites"]]
WT02.AR.peak.overlap.index <- findOverlaps(FPdata.AR.WT02.inputSites, WT02.peaks)
AR.WT02.idx <- unique(WT02.AR.peak.overlap.index@from)

FPdata.AR.CR01 <- FPdata.AR[["CR01"]]
FPdata.AR.CR01.inputSites <- FPdata.AR.CR01[["inputSites"]]
CR01.AR.peak.overlap.index <- findOverlaps(FPdata.AR.CR01.inputSites, CR01.peaks)
AR.CR01.idx <- unique(CR01.AR.peak.overlap.index@from)

FPdata.AR.CR02 <- FPdata.AR[["CR02"]]
FPdata.AR.CR02.inputSites <- FPdata.AR.CR02[["inputSites"]]
CR02.AR.peak.overlap.index <- findOverlaps(FPdata.AR.CR02.inputSites, CR02.peaks)
AR.CR02.idx <- unique(CR02.AR.peak.overlap.index@from)

FPdata.AR.CR04 <- FPdata.AR[["CR04"]]
FPdata.AR.CR04.inputSites <- FPdata.AR.CR04[["inputSites"]]
CR04.AR.peak.overlap.index <- findOverlaps(FPdata.AR.CR04.inputSites, CR04.peaks)
AR.CR04.idx <- unique(CR04.AR.peak.overlap.index@from)

FPdata.AR.CR05 <- FPdata.AR[["CR05"]]
FPdata.AR.CR05.inputSites <- FPdata.AR.CR05[["inputSites"]]
CR05.AR.peak.overlap.index <- findOverlaps(FPdata.AR.CR05.inputSites, CR05.peaks)
AR.CR05.idx <- unique(CR05.AR.peak.overlap.index@from)

FPdata.AR.CR07 <- FPdata.AR[["CR07"]]
FPdata.AR.CR07.inputSites <- FPdata.AR.CR07[["inputSites"]]
CR07.AR.peak.overlap.index <- findOverlaps(FPdata.AR.CR07.inputSites, CR07.peaks)
AR.CR07.idx <- unique(CR07.AR.peak.overlap.index@from)

FPdata.AR.CR08 <- FPdata.AR[["CR08"]]
FPdata.AR.CR08.inputSites <- FPdata.AR.CR08[["inputSites"]]
CR08.AR.peak.overlap.index <- findOverlaps(FPdata.AR.CR08.inputSites, CR08.peaks)
AR.CR08.idx <- unique(CR08.AR.peak.overlap.index@from)



newmatrix <- matrix(data = 0, nrow = 8, ncol = 62585)
rownames(newmatrix) <- c("WT01", "WT02", "CR01", "CR02", "CR04", "CR05", "CR07", "CR08")
newmatrix[1,AR.WT01.idx] <- 1
newmatrix[2,AR.WT02.idx] <- 1
newmatrix[3,AR.CR01.idx] <- 1
newmatrix[4,AR.CR02.idx] <- 1
newmatrix[5,AR.CR04.idx] <- 1
newmatrix[6,AR.CR05.idx] <- 1
newmatrix[7,AR.CR07.idx] <- 1
newmatrix[8,AR.CR08.idx] <- 1

pheatmap(newmatrix[,1:100],
         cluster_rows = FALSE,
         cluster_cols = FALSE)










AR.matrix <- FPdata.AR[["bindingMatrix"]]
x <- AR.matrix[,AR.WT01.idx]
pheatmap(x[,100:200])

y <- as.data.frame(AR.matrix)
z <- dplyr::filter(y, WT01 == 1, WT02 == 2)

aa <- which(y[1,] == 1 & y[2,] == 1)
ab <- which(y[1,] == 0 & y[2,] == 0)
ac <- c(aa, ab)
new <- y[1:8,ac]

new2 <- new[,24728:24828]
pheatmap(new2,
         cluster_rows = FALSE,
         cluster_cols = FALSE)





```


Replicate Peaks
```{r}




```

